Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu2204"
    config.vm.hostname = 'ubuntu'
    config.vm.synced_folder '.', '/vagrant', disabled: true

    config.ssh.username = "vagrant"
    config.ssh.password = "<PASSWORD>"
  
    config.vm.provider "hyperv" do |hyperv|
      hyperv.vmname = "Ubuntu"
      hyperv.cpus = "2"
      hyperv.memory = "4096"
      hyperv.maxmemory = "4096"
      hyperv.enable_enhanced_session_mode = true
    end
  
    config.vm.network "public_network", bridge: "External Switch"
end